yolo_model:

  config_file:
    name: yolov3_cone.cfg
  weight_file:
    name: yolov3_custom_cone.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - yellow cone
      - blue cone
